global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          instance: 'node-1'

  - job_name: 'my-app'
    static_configs:
      - targets: ['localhost:8080']
